[package]
name = "surround_virtualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0"
hdf5 = "0.8.1"
ndarray = "0.15.6"
plotters = "0.3.4"